/**
 * Client for the Pagefind-backed search panel.
 *
 * Pagefind's bundle only exists in the deployed site (the workflow generates it
 * after `quartz build`), so it is imported lazily on first use — a local build
 * without the index still renders, the panel just reports that search is
 * unavailable instead of throwing.
 *
 * Quartz is an SPA: this runs again after every navigation, so every listener
 * is registered through `addCleanup`.
 */

interface PagefindSubResult {
  url: string
  excerpt: string
}

interface PagefindResultData {
  url: string
  meta: { title?: string }
  excerpt: string
  sub_results?: PagefindSubResult[]
}

interface PagefindApi {
  options(opts: Record<string, unknown>): Promise<void>
  debouncedSearch(
    query: string,
    ms?: number,
  ): Promise<{ results: { data(): Promise<PagefindResultData> }[] } | null>
}

let pagefind: PagefindApi | null = null
let loadFailed = false

async function getPagefind(base: string): Promise<PagefindApi | null> {
  if (pagefind || loadFailed) return pagefind
  try {
    // Vite/esbuild must not try to resolve this at build time — the file is
    // generated by the Pagefind CLI long after the bundle is written.
    pagefind = (await import(/* @vite-ignore */ `${base}/pagefind/pagefind.js`)) as PagefindApi
    await pagefind.options({ excerptLength: 24 })
  } catch {
    loadFailed = true
  }
  return pagefind
}

/** Pagefind indexes the built HTML, so its URLs carry `.html` and the base path. */
function pageUrl(base: string, url: string): string {
  const clean = url.replace(/index\.html$/, "").replace(/\.html$/, "")
  return clean.startsWith(base) ? clean : base + clean
}

function resultCard(base: string, data: PagefindResultData): HTMLElement {
  const el = document.createElement("a")
  el.classList.add("result-card")
  el.href = pageUrl(base, data.url)

  const title = document.createElement("h3")
  title.textContent = data.meta.title ?? decodeURIComponent(data.url)

  const excerpt = document.createElement("p")
  excerpt.classList.add("description")
  // Pagefind's excerpt carries <mark> around the hit; it is generated from the
  // indexed text, not from user input, so keeping the markup is safe here.
  excerpt.innerHTML = data.sub_results?.[0]?.excerpt ?? data.excerpt

  el.append(title, excerpt)
  return el
}

document.addEventListener("nav", async () => {
  const root = document.querySelector<HTMLElement>(".pagefind-search")
  if (!root) return

  const base = root.dataset.base ?? ""
  const button = root.querySelector<HTMLButtonElement>("#pagefind-open")
  const container = root.querySelector<HTMLElement>("#pagefind-container")
  const input = root.querySelector<HTMLInputElement>("#pagefind-input")
  const output = root.querySelector<HTMLElement>("#pagefind-results")
  if (!button || !container || !input || !output) return

  function close() {
    container!.hidden = true
    input!.value = ""
    output!.innerHTML = ""
    document.body.classList.remove("no-mix-blend-mode")
  }

  function open() {
    container!.hidden = false
    document.body.classList.add("no-mix-blend-mode")
    input!.focus()
  }

  async function onInput() {
    const query = input!.value.trim()
    if (query.length < 2) {
      output!.innerHTML = ""
      return
    }

    const api = await getPagefind(base)
    if (!api) {
      output!.innerHTML = `<p class="search-status">Search index unavailable in this build.</p>`
      return
    }

    const search = await api.debouncedSearch(query, 120)
    // A newer keystroke superseded this query.
    if (search === null) return

    const data = await Promise.all(search.results.slice(0, 20).map((r) => r.data()))
    output!.innerHTML = ""
    if (data.length === 0) {
      output!.innerHTML = `<p class="search-status">No results for “${query.replace(/</g, "&lt;")}”.</p>`
      return
    }
    for (const d of data) output!.append(resultCard(base, d))
  }

  function onKey(e: KeyboardEvent) {
    if (e.key === "Escape" && !container!.hidden) {
      e.preventDefault()
      close()
      return
    }
    if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === "k") {
      e.preventDefault()
      container!.hidden ? open() : close()
    }
  }

  function onBackdrop(e: MouseEvent) {
    if (e.target === container) close()
  }

  button.addEventListener("click", open)
  input.addEventListener("input", onInput)
  container.addEventListener("click", onBackdrop)
  document.addEventListener("keydown", onKey)

  window.addCleanup?.(() => {
    button.removeEventListener("click", open)
    input.removeEventListener("input", onInput)
    container.removeEventListener("click", onBackdrop)
    document.removeEventListener("keydown", onKey)
  })
})
